### ISSUE TITLE
OSTUDIORX-RSTATIC#1: deploy 'rstatic' host

### ISSUE THREAD

**Issue by joseosuna** [ostudiorx/rstatic#1]
# Details
**Story Points:**  1 point.

# Description
We need a host to deploy our static resources such as logos, images, docs and others. Our host most be located in http://rstatic.ostudiorx.com.

**User:** Search engines.
**I Want:** Static information about the website is enabled.
**In order to:** Search engines can read it.

**Criteria:**
1. Write URI in a browser and verify each static resource is enabled.

**Examples:**
http://rstatic.ostudiorx.com/logo.gif. 
http://rstatic.ostudiorx.com/copyright.xhtml

# Issue Links
**Cloners**
This issue *clones*:
[RSTATIC#1: deploy 'rstatic' host](https://github.com/reddepruebas/rstatic/issues/1)

This issue is cloned by:
[OSTUDIORX-ATHRECORDS#1: deploy 'athrecords' host](https://github.com/ostudiorx/athrecords/issues/1)

# Sub-Tasks
1. [x] [OSTUDIORX-RSTATIC#2: Create a Jboss 7.1 engine in OpenShift.](https://github.com/ostudiorx/rstatic/issues/2)
2. [x] [OSTUDIORX-RSTATIC#3: Add an alias in Open Shift.](https://github.com/ostudiorx/rstatic/issues/3)
3. [x] [OSTUDIORX-RSTATIC#4: Add a CNAME in DNS hosting.](https://github.com/ostudiorx/rstatic/issues/4)
4. [x] [OSTUDIORX-RSTATIC#5: Clone Open Shift Project.](https://github.com/ostudiorx/rstatic/issues/5)
5. [x] [OSTUDIORX-RSTATIC#6: Load static resources.](https://github.com/ostudiorx/rstatic/issues/6)
6. [x] [OSTUDIORX-RSTATIC#7: Link code to GitHub.](https://github.com/ostudiorx/rstatic/issues/7)

# Time Tracking
**Date Started:** May 07, 2015.
**Time Spent:** *(eg. 3w 4d 12h)* 2h 20m.
